[package]
name = "pouch-yew-example"
version = "0.0.2"
authors = ["Horst Schwarz <horst.schwarz@joydev.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
yew = "0.17"
yewtil = "0.3"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4.21"
pouch = { path = "../.." }

