[package]
name = "pouch-yew-example"
version = "0.0.1"
authors = ["Horst Schwarz <horst.schwarz@joydev.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
yew = "0.17"
wasm-bindgen = "0.2"
pouch = { path = "../.." }

